version: '3.7'

services:
  bot:
    image: chevychelovna/currency-monitoring-bot
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - FIXER_API_KEY=${FIXER_API_KEY}
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: currency_monitoring
    networks:
      - app-network
    ports:
      - "5432:5432"

networks:
  app-network:
    driver: bridge
